console/routes/open.py
from flask import request, Blueprint, make_response, jsonify, session, redirect, flash, render_template, url_for

from console.config.config import Config

b_open = Blueprint("b_open", __name__)


def read_users():
    users = []
    with open(Config.USERS_PATH, "r") as infile:
        for line in infile.readlines():
            user = line.split("=")
            users.append({"uname":user[0], "pw":user[1]})
    return users


@b_open.route("/login", methods=["GET"])
def login_view():
    return render_template("login.html")

@b_open.route("/logout", methods=["GET"])
def logout():
    try:
        session.pop('logged_in_user')
        return redirect(url_for('b_open.login_view'))
    except Exception as e:
        return redirect(url_for('b_open.login_view'))


@b_open.route("/login", methods=["POST"])
def login_post():
    users = read_users()
    uname = request.form['username']
    pw = request.form['password']
    for user in users:
        if user['uname'] == uname and user['pw'] == pw:
            session['logged_in_user'] = user['uname']
            return redirect(url_for("b_routes.console"))
    else:
        flash(u'wrong username or password', 'login_error')
        return render_template("login.html")

console/templates/console.html
{%extends 'layout.html'%}
{%block console%}
<div class="casual-content collapsable {{'collapsed' if collapse}}">

  {%include 'nav/topnavigation.html'%}

  {%block content%}


  <div class="particle">
    <div class="particle-head"><span>Casual Console</span></div>
    <div class="particle-body">

      <div id="loader" style="margin:auto;">
        <img src={{url_for('static', filename="img/casual_symbol_BW.svg")}} alt="" class="rotating">
      </div>
      <p style="margin:auto;">Casual Admin Console powered by Python</p>
    </div>
  </div>


  {%endblock%}


  {%endblock%}

console/templates/inner_layout.html
{% extend 'layout.html'%}

{% block inner_layout %}

{% endblock %}

console/templates/layout.html
<!DOCTYPE html>
<html>

<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <title>{%block title%} Casual Console {%endblock%}</title>
  <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}">

  {% assets 'casual_css' %}
  <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}
  {%assets "lib_js"%}
  <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  {% block css%} {% endblock %}
</head>

<body>
  <div id="app">
    {%block casual%}
    <div class="casual">
      {% include 'nav/sidenavigation.html' %}
      {% block console %} base console {% endblock %}
    </div>
    {% endblock %}
  </div>
    {%assets "casual_js"%}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
</body>

</html>

console/templates/login.html
{%extends 'layout.html'%}
{%include 'nav/topnavigation.html'%}
{%block casual%}


<div class="casual">
  <div class="login-container">
    <div class="login-card card">
      <div class="login-logo"><span id="logo-icon"></span></div>

      <div class="login-body card-body">
        <form class="login-form" method="POST" action="{{url_for('b_open.login_post')}}">
          <div class="login username">
            <label for="username">Username</label>
            <input name="username" type="text" class="login-input username" maxlength="25" id="uname" autocomplete="off"
              autocapitalize="none" />
          </div>
          <div class="login password">
            <label for="password">Password</label>
            <input name="password" type="password" class="login-input password" maxlength="25" id="pw" />
          </div>
          <button type="submit" class="button form">Log in</button>

          {% with messages = get_flashed_messages(category_filter=["login_error"]) %}
          {% if messages %}
          <ul class=flashes>
            {% for message in messages %}
            <li class="error-message">{{ message }}</li>
            {% endfor %}
          </ul>
          {% endif %}
          {% endwith %}
          {%block login_message%}
          <div class="error-input" v-if="wrong">{{error_message}}</div>
          {%endblock%}
        </form>
      </div>
    </div>
  </div>

</div>


{%endblock%}