console/routes/views.py
import sys
from flask import render_template, Flask, request, Response, jsonify, make_response
from flask import Blueprint, redirect, session, url_for, flash
import json


import console.state.information as info
import console.state.update as update

import console.routes.api as api

b_routes = Blueprint("b_routes", __name__)


@b_routes.route("/")
def console():
    return render_template('console.html')


@b_routes.route("/servers")
def servers():
    servers = info.get_servers()
    return render_template('particles/server/servers.html', servers=servers)


@b_routes.route("/servers/server")
def get_server():
    try:
        alias = request.args.get('alias', default=None)
        tab = request.args.get('tab', default='conf')
        if tab == '':
            tab = 'conf'

        server = info.get_server_by_alias(alias)

        return render_template("particles/server/server.html", server=server, tabs=[dict(title='Configuration', short='conf'), dict(title='Environment', short='env'), dict(title='Services', short='serv'), dict(title='Member of', short="mem")], activeTab=tab)
    except Exception as e:
        return render_template("particles/errors/server_error.html")


@b_routes.route("/executables")
def get_executables():
    executables = info.get_executables()

    return render_template('particles/server/executables.html', executables=executables)


@b_routes.route("/executables/executable")
def get_executable():
    alias = request.args.get('alias', default=None)
    tab = request.args.get('tab', default='conf')
    if tab == '':
        tab = 'conf'
    executable = info.get_executable_by_alias(alias)

    return render_template('particles/server/executable.html', server=executable, tabs=[dict(title='Configuration', short='conf'), dict(title='Environment', short='env'), dict(title='Member of', short="mem")], activeTab=tab)


@b_routes.route("/groups")
def groups():
    try:
        groups = info.get_groups()
        return render_template('particles/group/groups.html', groups=groups)
    except Exception as e:
        return render_template('particles/errors/groups_error.html')


@b_routes.route("/groups/group")
def get_group():
    name = request.args.get('name', default=None)
    # print(name)
    group = info.get_group_by_name(name)

    return render_template("particles/group/group.html", group=group)


@b_routes.route("/services")
def get_services():
    try:
        page = int(request.args.get('page', default=1))
        category_filter = request.args.get('category', default='all')
        max_rows = int(request.args.get('rows', default=10))
        filters = [page, category_filter, max_rows]
        services = info.get_services(filters)

        return render_template("particles/service/services.html", services=services[0]['services'], categories=services[1], pages=services[0]['pages'], total=services[2])
    except Exception as e:
        return render_template("particles/errors/services_error.html", error=e)


@b_routes.route("/services/service")
def get_service():
    try:
        name = request.args.get('name', default=None)
        service = info.get_service_by_name(name)
        return render_template("particles/service/service.html", service=service)
    except Exception as e:
        return render_template("particles/errors/service_error.html")


@b_routes.route("/gateways")
def get_gateways():
    try:
        gateways = info.get_gateways()
        return render_template("particles/gateway/gateways.html", connections=gateways[0], listeners=gateways[1])
    except Exception as e:
        return render_template("500.html", error=e)

@b_routes.route("/transactions")
def get_transactions():
    transactions = info.get_transactions()
    try:
        template = render_template(
            "particles/transaction/transactions.html", transactions=transactions)

        return template
    except Exception as e:
        return render_template("500.html", error=e)



@b_routes.route("/ajaxtest", methods=["POST","GET"])
def ajax_test():

    return "My Response brings all the boys to the yard"

@b_routes.before_request
def check_before_test():
    pass
@b_routes.before_request
def check_cookies():
  session['collapsed'] = request.cookies.get('collapsed')


@b_routes.before_request
def is_logged_in():
  if 'logged_in_user' not in session:
    return redirect(url_for("b_open.login_view"))

@b_routes.context_processor
def inject_stuff():
  def check_collapsed(collapse = True):
    coll = False
    if 'collapsed' in session:
      coll = session.get('collapsed')
    else:
      session['collapsed'] = collapse
      coll = collapse
    return True if coll == 'true' else False


  collapsed = check_collapsed()
  return dict(collapse=collapsed)


def get_blueprints():
    return b_routes, api.b_api

console/templates/particles/service/service.html
{%extends 'particles/particle_wrapper.html'%}
{%block title%}Service | {{service.name}}{%endblock%}
{%block particle_head%}Service{%endblock%}
{%block particle%}
<div class="card">
  <div class="card-head">
    <span>info</span>
  </div>
  <div class="card-body">
    <div class="key-value-item">
      <span>name:</span> <span>{{ service.name }}</span>
    </div>
    <div class="key-value-item odd">
      <span>category:</span> <span>{{ service.category }}</span>
    </div>
    <div class="key-value-item">
      <span>parent server:</span>
      <span>

        {%if service.parent_server != 'unknown'%}

        <a href={{url_for("b_routes.get_server", alias=service.parent_server)}} class="particle-link">{{ service.parent_server }}</a>
        {%else%}
        <span>Unknown</span>
        {%endif%}
      </span>

    </div>
    <div class="key-value-item odd">
      <span>transaction:</span>
      <span>{{ service.transaction }}</span>
    </div>
    <div class="key-value-item">
      <span>timeout:</span> <span>{{ service.timeout }}</span>
    </div>
  </div>
</div>


{%include 'particles/service/service_metrics.html'%}

{%endblock%}

console/templates/particles/service/service_filters.html
<div class="card">
  <div class="row" id="service-filters">
    <div class="col select">
      Category: <select name="sort" id="filter-category">
        <option value="all">Show all</option>
        {% for category in categories %}
        <option value="{{category}}">
          {{category}}
        </option>
        {%endfor%}
      </select>
    </div>
    <div class="col select">
      Rows: <select name="rows" id="filter-rows">
        <option value="10">10</option>
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
        <option value="1000">1000</option>
      </select>
    </div>
    <div class="col">
      Page: <ul id="filter-page">

        {%for page in range(pages) %}
        <div class="button button--text h-no-margin-vert" onclick='gotoPage("{{page+1}}")'><span>{{page+1}}</span></div>
        {%endfor%}
      </ul>
    </div>
    <div class="col">
      <div class="button button--small right" onclick="resetFilters()"><span>Reset filters</span></div>
      <div class="button button--small right" onclick="applyFilters()"><span>Apply</span></div>
    </div>
  </div>
</div>


<script>

  function setSelect() {

    const params = new URLSearchParams(window.location.search);
    const category = params.get('category');
    const rows = params.get('rows');
    const page = params.get('page');
    if (category) {
      let categorySelect = document.getElementById("filter-category");
      categorySelect.value = category;
    }
    if (rows) {
      let rowsSelect = document.getElementById("filter-rows");
      rowsSelect.value = rows;
    }
    if(page) {
      
      let pageSelect = document.getElementById("filter-page");
      pageSelect.value = page;
    }

  }
  setSelect();

</script>

console/templates/particles/service/service_metrics.html
{%set count = service.metric.invoked.count%}
{%set pending_count = service.metric.pending.count%}
{%set total = service.metric.invoked.total/billion%}
{%set pending_total = service.metric.pending.total/billion%}
{%set min = service.metric.invoked.limit.min/billion %}
{%set max = service.metric.invoked.limit.max/billion %}
{%set pending_min = service.metric.pending.limit.min/billion %}
{%set pending_max = service.metric.pending.limit.max/billion %}
{%set avg = ((total / count) / billion) if count > 0 else 0%}
{%set pending_avg = ((pendin_total / pending_count) / billion) if pending_count > 0 else 0%}
{%set last = service.metric.last / billion%}

<div class="card">
  <div class="card-head">
    metrics
  </div>
  <div class="card-body">
    <div class="key-value-item">
      <span>last</span>
      <span>{{last | epochToDate}}</span>
    </div>
    <div class="key-value-item odd">
      <span>remote </span>
      <span>{{service.metric.remote}}</span>
    </div>
  </div>
</div>
<div class="card-stack child">
  <div class="card">
    <div class="card-head">
      invoked
    </div>
    <div class="card-body">
      <div class="key-value-item ">
        <span>count:</span>
        <span>{{count}}</span>
      </div>
      <div class="key-value-item odd">
        <span>total:</span>
        <span>{{total | formatMicroSec }}</span>
      </div>
    </div>
    <div class="key-value-item ">
      <span>min:</span>
      <span>{{min | formatMicroSec }}</span>
    </div>
    <div class="key-value-item odd">
      <span>max:</span>
      <span>{{max | formatMicroSec }}</span>
    </div>
  </div>
  <div class="card">
    <div class="card-head">
      pending
    </div>
    <div class="card-body">
      <div class="key-value-item">
        <span>count:</span>
        <span>{{pending_count}}</span>
      </div>
      <div class="key-value-item odd">
        <span>total:</span>
        <span>{{pending_total | formatMicroSec }}</span>
      </div>
      <div class="key-value-item">
        <span>min:</span>
        <span>{{pending_min | formatMicroSec}}</span>
      </div>
      <div class="key-value-item odd">
        <span>max:</span>
        <span>{{pending_max | formatMicroSec }}</span>
      </div>
    </div>

  </div>
</div>

console/templates/particles/service/services.html
{%extends 'particles/particle_wrapper.html'%}
{%block title%}Services{%endblock%}

{%block particle_head%}Services: {{services|length}} ({{total}}) {%endblock%}
{%block particle%}

{%include 'particles/service/service_filters.html'%}


<div class="card">

  {% include 'particles/service/services_table.html' %}
</div>

{%endblock%}

console/templates/particles/service/services_table.html
  <table class="particle-table">
    <thead>
      <tr class="particle-table-head">
        <th>name</th>
        <th>category</th>
        <th>call</th>
        <th>average</th>
        <th>min</th>
        <th>max</th>
        <th>pending</th>
        <th>pending avg</th>
        <th>last</th>
      </tr>
    </thead>
    <tbody>
      {%for service in services%}
      
      {%set count = service.metric.invoked.count%}
      {%set pending_count = service.metric.pending.count%}
      {%set total = service.metric.invoked.total%}
      {%set pending_total = service.metric.pending.total%}
      {%set min = service.metric.invoked.limit.min/billion %}
      {%set max = service.metric.invoked.limit.max/billion %}
      {%set avg = ((total / count) / billion) if count > 0 else 0%}
      {%set pending_avg = ((pending_total / pending_count) / billion) if pending_count > 0 else 0%}
      
      {%set last = service.metric.last / billion%}
      
      
      <tr class="particle-list-item {{'dark' if loop.index % 2 == 0}}">
        <td><a href={{url_for("b_routes.get_service", name=service.name)}} class="particle-link">{{service.name}}</a>
        </td>
        <td>{{service.category}}</td>
        <td>{{service.metric.invoked.count}}</td>
        <td>{{avg | formatMicroSec}}</td>
        <td>{{min | formatMicroSec}}</td>
        <td>{{max | formatMicroSec}}</td>
        <td>{{pending_count}}</td>
        <td>{{pending_avg | formatMicroSec}}</td>
        <td>{{last | epochToDate}}</td>
      </tr>
      {%endfor%}
    </tbody>
  </table>