console/routes/open.py
from flask import request, Blueprint, make_response, jsonify, session, redirect, flash, render_template, url_for

from console.config.config import Config

b_open = Blueprint("b_open", __name__)


def read_users():
    users = []
    with open(Config.USERS_PATH, "r") as infile:
        for line in infile.readlines():
            user = line.split("=")
            users.append({"uname":user[0], "pw":user[1]})
    return users


@b_open.route("/login", methods=["GET"])
def login_view():
    return render_template("login.html")

@b_open.route("/logout", methods=["GET"])
def logout():
    try:
        session.pop('logged_in_user')
        return redirect(url_for('b_open.login_view'))
    except Exception as e:
        return redirect(url_for('b_open.login_view'))


@b_open.route("/login", methods=["POST"])
def login_post():
    users = read_users()
    uname = request.form['username']
    pw = request.form['password']
    for user in users:
        if user['uname'] == uname and user['pw'] == pw:
            session['logged_in_user'] = user['uname']
            return redirect(url_for("b_routes.console"))
    else:
        flash(u'wrong username or password', 'login_error')
        return render_template("login.html")

console/routes/views.py
import sys
from flask import render_template, Flask, request, Response, jsonify, make_response
from flask import Blueprint, redirect, session, url_for, flash
import json


import console.state.information as info
import console.state.update as update

import console.routes.api as api

b_routes = Blueprint("b_routes", __name__)


@b_routes.route("/")
def console():
    return render_template('console.html')


@b_routes.route("/servers")
def servers():
    servers = info.get_servers()
    return render_template('particles/server/servers.html', servers=servers)


@b_routes.route("/servers/server")
def get_server():
    try:
        alias = request.args.get('alias', default=None)
        tab = request.args.get('tab', default='conf')
        if tab == '':
            tab = 'conf'

        server = info.get_server_by_alias(alias)

        return render_template("particles/server/server.html", server=server, tabs=[dict(title='Configuration', short='conf'), dict(title='Environment', short='env'), dict(title='Services', short='serv'), dict(title='Member of', short="mem")], activeTab=tab)
    except Exception as e:
        return render_template("particles/errors/server_error.html")


@b_routes.route("/executables")
def get_executables():
    executables = info.get_executables()

    return render_template('particles/server/executables.html', executables=executables)


@b_routes.route("/executables/executable")
def get_executable():
    alias = request.args.get('alias', default=None)
    tab = request.args.get('tab', default='conf')
    if tab == '':
        tab = 'conf'
    executable = info.get_executable_by_alias(alias)

    return render_template('particles/server/executable.html', server=executable, tabs=[dict(title='Configuration', short='conf'), dict(title='Environment', short='env'), dict(title='Member of', short="mem")], activeTab=tab)


@b_routes.route("/groups")
def groups():
    try:
        groups = info.get_groups()
        return render_template('particles/group/groups.html', groups=groups)
    except Exception as e:
        return render_template('particles/errors/groups_error.html')


@b_routes.route("/groups/group")
def get_group():
    name = request.args.get('name', default=None)
    # print(name)
    group = info.get_group_by_name(name)

    return render_template("particles/group/group.html", group=group)


@b_routes.route("/services")
def get_services():
    try:
        page = int(request.args.get('page', default=1))
        category_filter = request.args.get('category', default='all')
        max_rows = int(request.args.get('rows', default=10))
        filters = [page, category_filter, max_rows]
        services = info.get_services(filters)

        return render_template("particles/service/services.html", services=services[0]['services'], categories=services[1], pages=services[0]['pages'], total=services[2])
    except Exception as e:
        return render_template("particles/errors/services_error.html", error=e)


@b_routes.route("/services/service")
def get_service():
    try:
        name = request.args.get('name', default=None)
        service = info.get_service_by_name(name)
        return render_template("particles/service/service.html", service=service)
    except Exception as e:
        return render_template("particles/errors/service_error.html")


@b_routes.route("/gateways")
def get_gateways():
    try:
        gateways = info.get_gateways()
        return render_template("particles/gateway/gateways.html", connections=gateways[0], listeners=gateways[1])
    except Exception as e:
        return render_template("500.html", error=e)

@b_routes.route("/transactions")
def get_transactions():
    transactions = info.get_transactions()
    try:
        template = render_template(
            "particles/transaction/transactions.html", transactions=transactions)

        return template
    except Exception as e:
        return render_template("500.html", error=e)



@b_routes.route("/ajaxtest", methods=["POST","GET"])
def ajax_test():

    return "My Response brings all the boys to the yard"

@b_routes.before_request
def check_before_test():
    pass
@b_routes.before_request
def check_cookies():
  session['collapsed'] = request.cookies.get('collapsed')


@b_routes.before_request
def is_logged_in():
  if 'logged_in_user' not in session:
    return redirect(url_for("b_open.login_view"))

@b_routes.context_processor
def inject_stuff():
  def check_collapsed(collapse = True):
    coll = False
    if 'collapsed' in session:
      coll = session.get('collapsed')
    else:
      session['collapsed'] = collapse
      coll = collapse
    return True if coll == 'true' else False


  collapsed = check_collapsed()
  return dict(collapse=collapsed)


def get_blueprints():
    return b_routes, api.b_api

console/templates/nav/sidenavigation.html
{%block sidenav%}
<div id="sidenav-nav" class="collapsable {{'collapsed' if collapse}}">
  <div class="logo">
    <a href={{url_for("b_routes.console")}}>
      <span id="logo-icon"></span>
    </a>
  </div>
  <ul id="sidenav-list">
    <li class="sidenav-list-item">
      <a href={{url_for("b_routes.groups")}}>
        <div class="side-nav-icon" id="groups"></div>
        <span>Groups</span>
      </a>
    </li>
    <li class="sidenav-list-item">
      <a href={{url_for("b_routes.servers")}}>
        <div class="side-nav-icon" id="servers"></div>

        <span id="servers">Servers</span>
      </a>
    </li>
    <li class="sidenav-list-item">
        <a href={{url_for("b_routes.get_executables")}}>
          <div class="side-nav-icon" id="executables"></div>

          <span id="executables">Executables</span>
        </a>
      </li>
    <li class="sidenav-list-item">
      <a href="/services">
        <div class="side-nav-icon" id="services"></div>

        <span id="services">Services</span>
      </a>
    </li>
    <li class="sidenav-list-item">
      <a href="/gateways">
        <div class="side-nav-icon" id="gateways"></div>

        <span id="gateways">Gateways</span>
      </a>
    </li>
    <li class="sidenav-list-item">
      <a href="/transactions">
        <div class="side-nav-icon" id="transactions"></div>

        <span id="transactions">Transactions</span>
      </a>
    </li>
  </ul>
  <button class="button collapse " onclick="collapse()">
    <span class="collapse-icon collapsable {{'collapsed' if collapse}}" id="collapse-icon"></span>
  </button>
</div>
{%endblock%}

console/templates/nav/topnavigation.html
<div id="topnav">
  <!--div class="logo" @click="goHome">
    <img src="@/assets/img/casual_left_BW.svg" />
  </div-->
  <div id="console-head-line">
    <b>Casual Console</b>
    <p id="version">Casual version: {{casual_version}}</p>
  </div>

  {%if 'logged_in_user' in session %}
  <span>User: {{session['logged_in_user']}}</span>
  <a href="{{url_for('b_open.logout')}}" class="button button--text logout">Log out</a>
  {%else%}
  <div>Not logged in</div>
  {%endif%}
</div>