console/routes/views.py
import sys
from flask import render_template, Flask, request, Response, jsonify, make_response
from flask import Blueprint, redirect, session, url_for, flash
import json


import console.state.information as info
import console.state.update as update

import console.routes.api as api

b_routes = Blueprint("b_routes", __name__)


@b_routes.route("/")
def console():
    return render_template('console.html')


@b_routes.route("/servers")
def servers():
    servers = info.get_servers()
    return render_template('particles/server/servers.html', servers=servers)


@b_routes.route("/servers/server")
def get_server():
    try:
        alias = request.args.get('alias', default=None)
        tab = request.args.get('tab', default='conf')
        if tab == '':
            tab = 'conf'

        server = info.get_server_by_alias(alias)

        return render_template("particles/server/server.html", server=server, tabs=[dict(title='Configuration', short='conf'), dict(title='Environment', short='env'), dict(title='Services', short='serv'), dict(title='Member of', short="mem")], activeTab=tab)
    except Exception as e:
        return render_template("particles/errors/server_error.html")


@b_routes.route("/executables")
def get_executables():
    executables = info.get_executables()

    return render_template('particles/server/executables.html', executables=executables)


@b_routes.route("/executables/executable")
def get_executable():
    alias = request.args.get('alias', default=None)
    tab = request.args.get('tab', default='conf')
    if tab == '':
        tab = 'conf'
    executable = info.get_executable_by_alias(alias)

    return render_template('particles/server/executable.html', server=executable, tabs=[dict(title='Configuration', short='conf'), dict(title='Environment', short='env'), dict(title='Member of', short="mem")], activeTab=tab)


@b_routes.route("/groups")
def groups():
    try:
        groups = info.get_groups()
        return render_template('particles/group/groups.html', groups=groups)
    except Exception as e:
        return render_template('particles/errors/groups_error.html')


@b_routes.route("/groups/group")
def get_group():
    name = request.args.get('name', default=None)
    # print(name)
    group = info.get_group_by_name(name)

    return render_template("particles/group/group.html", group=group)


@b_routes.route("/services")
def get_services():
    try:
        page = int(request.args.get('page', default=1))
        category_filter = request.args.get('category', default='all')
        max_rows = int(request.args.get('rows', default=10))
        filters = [page, category_filter, max_rows]
        services = info.get_services(filters)

        return render_template("particles/service/services.html", services=services[0]['services'], categories=services[1], pages=services[0]['pages'], total=services[2])
    except Exception as e:
        return render_template("particles/errors/services_error.html", error=e)


@b_routes.route("/services/service")
def get_service():
    try:
        name = request.args.get('name', default=None)
        service = info.get_service_by_name(name)
        return render_template("particles/service/service.html", service=service)
    except Exception as e:
        return render_template("particles/errors/service_error.html")


@b_routes.route("/gateways")
def get_gateways():
    try:
        gateways = info.get_gateways()
        return render_template("particles/gateway/gateways.html", connections=gateways[0], listeners=gateways[1])
    except Exception as e:
        return render_template("500.html", error=e)

@b_routes.route("/transactions")
def get_transactions():
    transactions = info.get_transactions()
    try:
        template = render_template(
            "particles/transaction/transactions.html", transactions=transactions)

        return template
    except Exception as e:
        return render_template("500.html", error=e)



@b_routes.route("/ajaxtest", methods=["POST","GET"])
def ajax_test():

    return "My Response brings all the boys to the yard"

@b_routes.before_request
def check_before_test():
    pass
@b_routes.before_request
def check_cookies():
  session['collapsed'] = request.cookies.get('collapsed')


@b_routes.before_request
def is_logged_in():
  if 'logged_in_user' not in session:
    return redirect(url_for("b_open.login_view"))

@b_routes.context_processor
def inject_stuff():
  def check_collapsed(collapse = True):
    coll = False
    if 'collapsed' in session:
      coll = session.get('collapsed')
    else:
      session['collapsed'] = collapse
      coll = collapse
    return True if coll == 'true' else False


  collapsed = check_collapsed()
  return dict(collapse=collapsed)


def get_blueprints():
    return b_routes, api.b_api

console/templates/particles/group/group.html
{%extends 'particles/particle_wrapper.html'%}
{%block title%}Group | {{group.name}}{%endblock%}
{%block particle_head%}Group{%endblock%}
{%block particle%}

<div class="card">
  <div class="card-head">info</div>
  <div class="card-body">
    <div class="key-value-item">
      <span>id:</span>
      <span>{{ group.id }}</span>
    </div>
    <div class="key-value-item odd">
      <span>name:</span>
      <span>{{ group.name }}</span>
    </div>
    <br />
  </div>
</div>
<div class="card">
  <div class="card-head">dependencies</div>

  
  {%with groups = group.group_dependencies%}

  {% if groups|length > 0 %}

  {%include 'particles/group/groups_table.html'%}
  {%else%}
  <div>No dependencies</div>
  {%endif%}

  {%endwith%}
</div>
{%set servers = group.server_members%}
{%set executables = group.executable_members%}
<div class="card slim">
  <div class="card-head">Members ({{servers|length + executables|length}})</div>

</div>
<div class="card-stack child">
  {%if servers  | length > 0%}
  <div class="card slim">
    <div class="card-head">Servers
    </div>
    <div class="card-body">
      {%include 'particles/group/members_table.html'%}
    </div>
  </div>
  {%endif%}

  {%if executables | length > 0%}
  <div class="card slim">
    <div class="card-head">Executables
    </div>

    <div class="card-body">
      {%with servers = executables%}
      {%include 'particles/group/members_table.html'%}

      {%endwith%}
    </div>
  </div>
  {%endif%}
  {%if servers | length < 1 and executables| length < 1 %}
  <div class="card">
    <div class="card-head">No members</div>
  </div>
  {%endif%}
</div>
</div>
</div>


{%endblock%}

console/templates/particles/group/groups.html
{%extends 'particles/particle_wrapper.html'%}
{%block title%}Groups {%endblock%}

{%block particle_head%}Groups: {{groups|length}} ({{groups|length}}){%endblock%}

{%block particle%}
<div class="card">
  {%include 'particles/group/groups_table.html'%}
</div>
{%endblock%}

console/templates/particles/group/groups_table.html
  <table class="particle-table">
    <thead>
      <tr class="particle-table-head">
        <th>name</th>
        <th>note</th>
        <th>members</th>
      </tr>
    </thead>
    <tbody>
      {%for item in groups%}
      <tr class="particle-list-item  {{'dark' if loop.index % 2 == 0}}">
        <td>
          <a class="particle-link" href={{url_for("b_routes.get_group", name=item.name)}}>
            {{item.name}}
          </a>
        </td>
        <td>
          {{item.note}}
        </td>
        <td>
          {{item.membercount}}
        </td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
  

console/templates/particles/group/members_table.html
  <div class="particle-table">
      <div class="row particle-table-head">
        <div class="col col-4">alias</div>
        <div class="col col-8">note</div>
      </div>
      {%for item in servers%}
      <div class="particle-list-item row {{'dark' if loop.index % 2 == 0}}">
        <div class="col col-4">
          <a class="particle-link" href={{url_for("b_routes.get_server", alias=item.alias)}}>{{item.alias}}</a>
        </div>
        <div class="col col-8">{{item.note}}</div>

      </div>
      {%endfor%}
    </div>